service: aws-payment-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.10
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, 'dev'}
  timeout: 29
  memorySize: 256 # Payment service can be leaner

  environment:
    BILLPLZ_X_SIGNATURE_KEY: ${env:BILLPLZ_X_SIGNATURE_KEY}
    CALLBACK_URL: ${env:CALLBACK_URL}
    REDIRECT_URL: ${env:REDIRECT_URL}
    MONGODB_MCP_URL: ${env:MONGODB_MCP_URL}
    DB_NAME: ${env:DB_NAME}
    COLLECTION_NAME: ${env:COLLECTION_NAME}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
          Resource: "arn:aws:logs:*:*:*"

functions:
  createBill:
    handler: payment_handler.create_bill
    events:
      - http:
          path: payment/create-bill
          method: post
          cors: true

  paymentWebhook:
    handler: payment_handler.handle_webhook
    events:
      - http:
          path: payment/webhook
          method: post

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements